# Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.


# Where to find user code.

PLUGINS_DIR = ./plugins
TEST_DIR = ./test

CRAWLER_SCHDULER = crawler_schduler
CRAWLER_TASK = crawler_task
FORGERY= forgery
LOGIN = login
MANAGER = manager

MAKE = make
CLEAN = make clean

all: crawler_schduler crawler_task forgery\
	login manager
	

crawler_schduler:
	cd $(PLUGINS_DIR)/$(CRAWLER_SCHDULER)&&$(CLEAN)&&$(MAKE)
	
crawler_task:
	cd $(PLUGINS_DIR)/$(CRAWLER_TASK)&&$(CLEAN)&&$(MAKE)
		
forgery:
	cd $(PLUGINS_DIR)/$(FORGERY)&&$(CLEAN)&&$(MAKE)
	
login:
	cd $(PLUGINS_DIR)/$(LOGIN)&&$(CLEAN)&&$(MAKE)
	
manager:
	cd $(PLUGINS_DIR)/$(MANAGER)&&$(CLEAN)&&$(MAKE)


	


